packageName: "org.example.pojo"
classes:
  FirstPojo:
    fields:
      firstField:
        annot1: true
      thirdField:
        annot2: true
      fourthField:
        annot1: true
        annot2: true
  SecondPojo: {}
